---
name: Mobile-Devices
version: 0.02
author:
  - 'Jozef Kutej <jozef@kutej.net>'
abstract: search for and get mobile device information
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Extract: 0
  Archive::Zip: 0
  Class::Accessor::Fast: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  Getopt::Long: 0
  LWP::Simple: 0
  Pod::Usage: 0
  Template: 0
  XML::Compile::Schema: 0
  XML::LibXML::Reader: 0
build_requires:
  Test::Differences: 0
  Test::More: 0
provides:
  Mobile::Devices:
    file: lib/Mobile/Devices.pm
    version: 0.02
  Mobile::Devices::Base:
    file: lib/Mobile/Devices/Base.pm
    version: 0.01
  Mobile::Devices::Loop:
    file: lib/Mobile/Devices/Loop.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
